"""
Decision Engine
Combines results from all analyzers into a unified trust decision.
Provides clear, human-readable classification with detailed reasoning.
"""

from typing import Any


# Weights for each analyzer (must sum to 1.0)
WEIGHTS = {
    "metadata": 0.20,
    "reverse_search": 0.30,
    "ai_detection": 0.30,
    "ela": 0.20,
}

# Trust-score thresholds
TRUST_SCORE_VERIFIED = 70     # >= this → "verified"
TRUST_SCORE_SUSPICIOUS = 40   # >= this (and < VERIFIED) → "suspicious"
                               # < SUSPICIOUS → "flagged"

# Classification score caps
TRUST_CAP_AI_GENERATED = 25
TRUST_CAP_WEB_SOURCED = 35
TRUST_CAP_EDITED = 50
TRUST_CAP_NO_EXIF = 30
TRUST_CAP_NO_CAMERA = 40

# Minimum trust score awarded when EXIF + ELA both pass (original boost)
TRUST_FLOOR_ORIGINAL = 90

# AI detection confidence thresholds
AI_CONFIDENCE_HIGH = 70   # >= this → definite AI image
AI_CONFIDENCE_MID = 50    # >= this (and < HIGH) → possible AI image
AI_CLASSIFICATION_THRESHOLD = 60  # used for classification priority

# ELA editing confidence thresholds
ELA_CONFIDENCE_HIGH = 60
ELA_CONFIDENCE_MID = 30
ELA_CLASSIFICATION_THRESHOLD = 50  # used for classification priority

# Reverse-search match count thresholds
REVERSE_MATCH_MANY = 5   # >= this → strong web-sourced signal
REVERSE_MATCH_FEW = 2    # >= this (and < MANY) → weak web-sourced signal
REVERSE_MATCH_CLASSIFICATION = 3  # >= this → classify as web-sourced

# Scores assigned when a service is unavailable
SCORE_SERVICE_UNAVAILABLE = 60  # neutral — no evidence either way
SCORE_NO_MATCHES = 90           # reward: image not found online

# Human-readable classification labels (Vietnamese + English)
CLASSIFICATION_INFO = {
    "original": {
        "label": "Original Photo",
        "label_vi": "Ảnh gốc",
        "description": "This image appears to be an original, unaltered photograph taken by a real camera.",
        "icon": "camera",
    },
    "web-sourced": {
        "label": "Web-Sourced Image",
        "label_vi": "Ảnh từ Internet",
        "description": "This image was found on the internet and may not be the seller's own photo.",
        "icon": "globe",
    },
    "edited": {
        "label": "Edited Image",
        "label_vi": "Ảnh đã chỉnh sửa",
        "description": "This image shows signs of digital editing or manipulation.",
        "icon": "paintbrush",
    },
    "ai-generated": {
        "label": "AI-Generated Image",
        "label_vi": "Ảnh do AI tạo",
        "description": "This image appears to be generated by artificial intelligence, not a real photograph.",
        "icon": "cpu",
    },
}


def _summarize_metadata(metadata_result: dict[str, Any]) -> dict[str, Any]:
    """Create a clear summary for EXIF metadata analysis."""
    has_exif = metadata_result.get("has_exif", False)
    camera = metadata_result.get("camera")
    software = metadata_result.get("software")
    gps = metadata_result.get("gps", False)
    score = metadata_result.get("score", 50)

    if not has_exif:
        verdict = "warn"
        score = max(score, 20)  # ensure low score
        summary = "⚠ No EXIF metadata found — image likely downloaded from the web or had metadata stripped. Original photos from cameras/phones always have EXIF data."
    elif camera and not metadata_result.get("ai_software_detected"):
        verdict = "pass"
        summary = f"Camera: {camera}."
        if gps:
            summary += " GPS location data present."
        if software:
            summary += f" Software: {software}."
    elif metadata_result.get("ai_software_detected"):
        verdict = "fail"
        summary = f"AI/editing tool detected in metadata: {software}."
    elif metadata_result.get("editing_software_detected"):
        verdict = "warn"
        summary = f"Editing software detected: {software}."
    else:
        verdict = "neutral"
        summary = "Metadata present but no camera info found."

    return {
        "name": "EXIF Metadata",
        "icon": "camera",
        "score": score,
        "verdict": verdict,
        "summary": summary,
    }


def _summarize_reverse_search(reverse_result: dict[str, Any]) -> dict[str, Any]:
    """Create a clear summary for reverse image search."""
    found = reverse_result.get("found", False)
    match_count = reverse_result.get("match_count", 0)
    score = reverse_result.get("score", 50)
    sources = reverse_result.get("sources", [])

    if not found and match_count == 0:
        # Check if search was actually performed
        details = reverse_result.get("details", [])
        if any("skipped" in d.lower() or "not configured" in d.lower() for d in details):
            # Service unavailable — treat as neutral, don't penalize
            verdict = "neutral"
            score = SCORE_SERVICE_UNAVAILABLE
            summary = "Reverse search not available — image origin not checked. This does not affect authenticity."
        else:
            verdict = "pass"
            score = SCORE_NO_MATCHES
            summary = "✓ No matches found online — this is a unique photo, likely taken directly by the seller."
    elif match_count >= REVERSE_MATCH_MANY:
        verdict = "fail"
        top_source = sources[0].get("source", "unknown") if sources else "unknown"
        summary = f"Found {match_count} matches online (e.g. {top_source}). Likely not an original photo."
    elif match_count >= REVERSE_MATCH_FEW:
        verdict = "warn"
        summary = f"Found {match_count} similar images online. May not be original."
    else:
        verdict = "neutral"
        summary = "1 similar image found — could be coincidental."

    return {
        "name": "Reverse Image Search",
        "icon": "globe",
        "score": score,
        "verdict": verdict,
        "summary": summary,
    }


def _summarize_ai_detection(ai_result: dict[str, Any]) -> dict[str, Any]:
    """Create a clear summary for AI generation detection."""
    is_ai = ai_result.get("is_ai", False)
    confidence = ai_result.get("confidence", 0)
    label = ai_result.get("label", "unknown")
    score = ai_result.get("score", 50)

    if is_ai and confidence > AI_CONFIDENCE_HIGH:
        verdict = "fail"
        summary = f"Classified as AI-generated with {confidence}% confidence. This is likely not a real photograph."
    elif is_ai and confidence > AI_CONFIDENCE_MID:
        verdict = "warn"
        summary = f"Possible AI-generated image ({confidence}% confidence). Requires further inspection."
    elif not is_ai and label == "Real":
        verdict = "pass"
        summary = f"Classified as a real photograph ({confidence}% confidence)."
    elif label == "unknown" and confidence == 0:
        # Model didn't load or returned no result — don't penalize
        verdict = "neutral"
        score = SCORE_SERVICE_UNAVAILABLE
        summary = "AI detection inconclusive — model did not return a result. This does not affect authenticity."
    else:
        verdict = "neutral"
        summary = f"AI detection result: {label} ({confidence}% confidence)."

    return {
        "name": "AI Detection",
        "icon": "cpu",
        "score": score,
        "verdict": verdict,
        "summary": summary,
    }


def _summarize_ela(ela_result: dict[str, Any]) -> dict[str, Any]:
    """Create a clear summary for ELA (Error Level Analysis)."""
    edited = ela_result.get("edited", False)
    confidence = ela_result.get("confidence", 0)
    suspicious_area = ela_result.get("suspicious_area_pct", 0)
    score = ela_result.get("score", 50)

    if edited and confidence > ELA_CONFIDENCE_HIGH:
        verdict = "fail"
        summary = f"Editing detected — {suspicious_area}% of the image has inconsistent compression levels ({confidence}% confidence)."
    elif edited and confidence > ELA_CONFIDENCE_MID:
        verdict = "warn"
        summary = f"Minor editing indicators — {suspicious_area}% suspicious area ({confidence}% confidence)."
    else:
        verdict = "pass"
        summary = "No significant editing detected. Compression levels are consistent throughout the image."

    return {
        "name": "Edit Detection (ELA)",
        "icon": "paintbrush",
        "score": score,
        "verdict": verdict,
        "summary": summary,
    }


def make_decision(
    metadata_result: dict[str, Any],
    reverse_result: dict[str, Any],
    ai_result: dict[str, Any],
    ela_result: dict[str, Any],
) -> dict[str, Any]:
    """
    Combine all analysis results into a final trust decision.
    
    Classification hierarchy:
    1. AI-Generated (if AI detector says so with high confidence)
    2. Web-Sourced (if reverse search finds substantial matches)
    3. Edited (if ELA detects manipulation)
    4. Original (if everything checks out)
    
    Returns unified decision with trust score 0-100 and clear per-analyzer summaries.
    """

    # Build per-analyzer summaries first (they may adjust scores)
    analyzer_summaries = [
        _summarize_metadata(metadata_result),
        _summarize_reverse_search(reverse_result),
        _summarize_ai_detection(ai_result),
        _summarize_ela(ela_result),
    ]

    # Use summarized scores (which handle unavailable services properly)
    meta_score = analyzer_summaries[0]["score"]
    rs_score = analyzer_summaries[1]["score"]
    ai_score = analyzer_summaries[2]["score"]
    ela_score = analyzer_summaries[3]["score"]

    # Calculate weighted score using adjusted analyzer scores
    weighted_score = (
        meta_score * WEIGHTS["metadata"]
        + rs_score * WEIGHTS["reverse_search"]
        + ai_score * WEIGHTS["ai_detection"]
        + ela_score * WEIGHTS["ela"]
    )

    trust_score = round(max(0, min(100, weighted_score)))

    # Boost: EXIF + ELA are the most reliable local checks.
    # If both pass, this is strong evidence of an authentic photo.
    meta_verdict = analyzer_summaries[0]["verdict"]
    ela_verdict = analyzer_summaries[3]["verdict"]
    rs_verdict = analyzer_summaries[1]["verdict"]
    ai_verdict = analyzer_summaries[2]["verdict"]

    # Determine classification based on strongest signal
    classification = "original"
    classification_reason = "All checks passed — image appears authentic."

    # Priority 1: AI-generated
    if ai_result.get("is_ai") and ai_result.get("confidence", 0) > AI_CLASSIFICATION_THRESHOLD:
        classification = "ai-generated"
        trust_score = min(trust_score, TRUST_CAP_AI_GENERATED)
        classification_reason = f"AI detector classified this as AI-generated with {ai_result.get('confidence', 0)}% confidence."

    # Priority 2: Web-sourced (via reverse search)
    elif reverse_result.get("found") and reverse_result.get("match_count", 0) >= REVERSE_MATCH_CLASSIFICATION:
        classification = "web-sourced"
        trust_score = min(trust_score, TRUST_CAP_WEB_SOURCED)
        match_count = reverse_result.get("match_count", 0)
        classification_reason = f"Found {match_count} identical/similar images online. This is likely downloaded from the internet."

    # Priority 3: Edited
    elif ela_result.get("edited") and ela_result.get("confidence", 0) > ELA_CLASSIFICATION_THRESHOLD:
        classification = "edited"
        trust_score = min(trust_score, TRUST_CAP_EDITED)
        classification_reason = f"Error Level Analysis detected editing with {ela_result.get('confidence', 0)}% confidence."

    # Priority 4: Web-sourced (via missing EXIF — no camera/phone produces images without EXIF)
    elif not metadata_result.get("has_exif", False):
        classification = "web-sourced"
        trust_score = min(trust_score, TRUST_CAP_NO_EXIF)
        classification_reason = (
            "No EXIF metadata found. Original photos from cameras and phones always "
            "contain EXIF data (camera model, date, etc). This image was likely "
            "downloaded from the internet or had its metadata stripped."
        )

    # Priority 5: Web-sourced (has EXIF but no camera info — likely screenshot or web)
    elif metadata_result.get("has_exif") and not metadata_result.get("camera"):
        classification = "web-sourced"
        trust_score = min(trust_score, TRUST_CAP_NO_CAMERA)
        classification_reason = (
            "EXIF metadata present but no camera information found. "
            "This image may be a screenshot or downloaded from the web."
        )

    # Apply boost ONLY if classification is still "original"
    if classification == "original" and meta_verdict == "pass" and ela_verdict == "pass":
        # Camera EXIF confirmed + no editing = very strong evidence of original
        trust_score = max(trust_score, TRUST_FLOOR_ORIGINAL)

    # Determine trust level
    if trust_score >= TRUST_SCORE_VERIFIED:
        trust_level = "verified"
    elif trust_score >= TRUST_SCORE_SUSPICIOUS:
        trust_level = "suspicious"
    else:
        trust_level = "flagged"

    # Get classification info
    cls_info = CLASSIFICATION_INFO.get(classification, CLASSIFICATION_INFO["original"])

    return {
        "classification": classification,
        "classificationLabel": cls_info["label"],
        "classificationLabelVi": cls_info["label_vi"],
        "classificationDescription": cls_info["description"],
        "classificationReason": classification_reason,
        "classificationIcon": cls_info["icon"],
        "trustScore": trust_score,
        "trustLevel": trust_level,
        # Per-analyzer detailed summaries
        "analyzers": analyzer_summaries,
        # Raw data for detailed views
        "metadata": {
            "hasExif": metadata_result.get("has_exif", False),
            "camera": metadata_result.get("camera"),
            "software": metadata_result.get("software"),
            "gps": metadata_result.get("gps", False),
        },
        "reverseSearch": {
            "found": reverse_result.get("found", False),
            "matchCount": reverse_result.get("match_count", 0),
            "sources": reverse_result.get("sources", []),
        },
        "aiDetection": {
            "isAI": ai_result.get("is_ai", False),
            "confidence": ai_result.get("confidence", 0),
        },
        "ela": {
            "edited": ela_result.get("edited", False),
            "confidence": ela_result.get("confidence", 0),
        },
        "details": (
            metadata_result.get("details", [])
            + reverse_result.get("details", [])
            + ai_result.get("details", [])
            + ela_result.get("details", [])
        ),
        "breakdown": {
            "metadata_score": metadata_result.get("score", 50),
            "reverse_search_score": reverse_result.get("score", 50),
            "ai_detection_score": ai_result.get("score", 50),
            "ela_score": ela_result.get("score", 50),
        },
    }
